# Build System
[build-system]
  requires = ["uv_build>=0.12,<0.13"]
  build-backend = "uv_build"

# Project Metadata
[project]
  name = "pyholdsport"
  version = "0.0.0"
  description = "Unofficial Python library for interacting with Holdsport."
  readme = "README.md"
  license = { file = "LICENSE" }
  authors = [{ name = "Daniel Mizsak", email = "daniel@mizsak.com" }]
  requires-python = ">=3.11"
  dependencies = ["httpx>=0.28.1", "pydantic>=2.12.5"]

  [project.urls]
    Repository = "https://github.com/daniel-mizsak/pyholdsport"
    Documentation = "https://daniel-mizsak.github.io/pyholdsport/"
    Issues = "https://github.com/daniel-mizsak/pyholdsport/issues"

[dependency-groups]
  dev = [
    "coverage==7.16.1",
    "nox==2026.8.17",
    "prek==0.5.3",
    "pytest==9.1.1",
    "respx==0.23.1",
    "ruff==0.16.7",
    "ty==0.0.81",
  ]
  docs = ["zensical==0.0.62", "mkdocstrings-python==2.0.8"]

# Tools
# Uv
[tool.uv]
  exclude-newer = "1 week"

  [tool.uv.build-backend]
    module-root = "src"
    module-name = "pyholdsport"
