# Exclude a variety of commonly ignored directories.
# exclude = [""]

line-length = 120
indent-width = 4

[lint]
  select = ["ALL"]
  ignore = [
    "D203",  # one-blank-line-before-class
    "D212",  # multi-line-summary-first-line
    "FIX",   # flake8-fixme
    "INP",   # flake8-no-pep420
    "S104",  # hardcoded-bind-all-interfaces
    "TD002", # missing-todo-author
    "TD003", # missing-todo-link
  ]
  [lint.per-file-ignores]
    "__init__.py" = [
      "D104", # undocumented-public-package
    ]
    "tests/**" = [
      "ANN001",  # missing-type-function-argument
      "ANN201",  # missing-return-type-undocumented-public-function
      "D",       # pydocstyle
      "PLR2004", # magic-value-comparison
      "PT001",   # pytest-fixture-incorrect-parentheses-style
      "S101",    # assert
    ]
    "docs_src/**" = [
      "D",    # pydocstyle
      "S106", # hardcoded-password-func-arg
      "T201", # print
    ]
  [lint.pydocstyle]
    convention = "google"
